FROM nspdemo.azurecr.io/nodejs/node:19 as node

WORKDIR /app
COPY package.json .
RUN npm install
COPY ./ .

RUN npm run test
# Run end to end tests to ensure that the image being built is valid
#RUN npm run e2e

ARG conf=production
RUN npm run build -- --configuration $conf

FROM nspdemo.azurecr.io/nginx/nginx:1.23.3-alpine
COPY --from=node /app/dist/benefits/ecmt /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf