FROM nspdemo.azurecr.io/nodejs/node:19 as builder

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

WORKDIR /app
COPY package.json package.json
COPY package-lock.json package-lock.json
COPY decorate-angular-cli.js decorate-angular-cli.js

RUN npm ci && npm cache clean --force
# RUN npm install
# RUN npm install --only=dev 
COPY . .
RUN npm run build shell -- --configuration $NODE_ENV

FROM nspdemo.azurecr.io/nginx/nginx:1.23.3-alpine
VOLUME /var/cache/nginx
COPY --from=builder /app/dist/apps/shell /usr/share/nginx/html
COPY nginx-default.conf /etc/nginx/conf.d/default.conf